# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        ('subjects', '0001_initial'),
        ('streames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('student_count', models.PositiveIntegerField()),
                ('degree_name', models.CharField(max_length=200)),
                ('apitude_exam', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('english', 'English'), ('tamil', 'Tamil'), ('sinhale', 'Sinhale')], default=None, max_length=50)),
                ('period', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4)),
                ('ordinary_level', models.BooleanField(default=False)),
                ('discription', models.TextField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streames.Stream')),
                ('subject1', models.ManyToManyField(related_name='subject1', to='subjects.Subject')),
                ('subject2', models.ManyToManyField(related_name='subject2', to='subjects.Subject')),
                ('subject3', models.ManyToManyField(related_name='subject3', to='subjects.Subject')),
                ('subject4', models.ManyToManyField(related_name='subject4', to='subjects.Subject')),
                ('subject5', models.ManyToManyField(related_name='subject5', to='subjects.Subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200)),
                ('zscore', models.DecimalField(decimal_places=4, max_digits=5)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
    ]
