# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181226_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unique_name',
            field=models.SlugField(blank=True),
        ),
    ]
