# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_unique_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='unique_name',
            new_name='slug',
        ),
    ]
