# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20181228_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='result4',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='result5',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject4',
            field=models.ManyToManyField(blank=True, default=None, related_name='subject4', to='subjects.Subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject5',
            field=models.ManyToManyField(blank=True, default=None, related_name='subject5', to='subjects.Subject'),
        ),
    ]
