# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181231_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='zscore',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
