# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181231_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='result4',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='result5',
            new_name='maths',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject5',
        ),
        migrations.AddField(
            model_name='course',
            name='science',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='S', max_length=1),
        ),
    ]
