# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20181231_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ordinary_level',
        ),
        migrations.AlterField(
            model_name='course',
            name='english',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='maths',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='result1',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='result2',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='result3',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='science',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='W', max_length=2),
        ),
    ]
