# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-13 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20190102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='district',
            field=models.CharField(blank=True, choices=[('Ampara', 'Ampara'), ('Anuradhepura', 'Anuradhepura'), ('Batticloa', 'Batticloa'), ('Badullah', 'Badullah'), ('Colombo', 'Colombo'), ('Kandy', 'Kandy'), ('Jaffna', 'Jaffna'), ('Kegalle', 'Kegalle'), ('Gampaha', 'Gampaha'), ('kilinochi', 'kilinochi'), ('Mullaithivu', 'Mullaithivu'), ('Trincomeli', 'Trincomeli'), ('Mannar', 'Mannar'), ('Polannaruwa', 'Polannaruwa'), ('Puttalam', 'Puttalam'), ('Galle', 'Galle'), ('Matara', 'Matara'), ('Hambandhota', 'Hambandhota'), ('Kalutara', 'Kalutara'), ('Monaragale', 'Monaragale'), ('Kurunegale', 'Kurunegale'), ('Nuwareliya', 'Nuwareliya'), ('Matale', 'Matale'), ('Ratnapura', 'Ratnapura'), ('Vavniya', 'Vavniya')], max_length=200),
        ),
    ]
