# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20181231_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ordinary_level',
        ),
    ]
