# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20181231_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='english',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='maths',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='W', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='science',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S'), ('W', 'W')], default='W', max_length=2),
        ),
    ]
