# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-26 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='stream',
        ),
    ]
