# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('moto', models.TextField()),
                ('website', models.URLField(max_length=1000)),
                ('facebook', models.URLField(max_length=1000)),
                ('linkedin', models.URLField(max_length=1000)),
                ('location', models.URLField(max_length=1000)),
                ('city', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('discription', models.TextField()),
                ('timstamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
