# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
