# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, upload_to='static/logo'),
        ),
    ]
