# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20181228_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, upload_to='logo'),
        ),
    ]
