# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-26 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('bio', 'biological_science'), ('maths', 'physical_science'), ('commerce', 'commerce'), ('arts', 'arts'), ('btech', 'bio_technology'), ('etech', 'engineering_technology'), ('others', 'others')], default=None, max_length=120)),
            ],
        ),
    ]
